### ISSUE TITLE
Docker-compose and volumes

### ISSUE THREAD

**Issue by Quentinvarquet** [webdevops/Dockerfile#145]
Hello,

I am using your docker image  webdevops/php-apache:debian-8-php7 but I have a problem when I use it with docker-compose.

Here is my configuration 

```
apache-php/
         docker-compose.yml
         www/
```

Here is my docker-compose.yml : 

```
version: '2'
services:

 apache:
  image: my_image_based_on_your
  volumes:
   - ./www:/app/
  ports:
   - 80:80
```

I created my own image from your dockerfile. I just added one line that will download a file and put it in /app

But when I do **docker-compose up -d** my **www/** folder is empty and the **app/** folder in the container is also empty.

If I delete the line **./www/app** in my **docker-compose.yml**, I have my test.html file in the **app/** folder in my container.

It looks like the images mount the volume **./www** but delete everything in *app/* . 

For example, if you try to mount this docker-compose.yml, the volume will be mounted and all the data will be inside the folder ./icinga/icingaweb2

Folder : 

```
icinga/
         docker-compose.yml
```

docker-compose.yml file

```
version : '2'
services:

 icinga:
  image: quentinv/icinga
  volumes:
   - ./icinga/icingaweb2:/etc/icingaweb2
  environment:
   - ICINGA_PASSWORD=test
   - ICINGA_WEB_PASSWORD=test
   - ICINGAWEB2_PASSWORD=test
   - IDO_PASSWORD=test
   - DIRECTOR_PASSWORD=test
   - DEBIAN_SYS_MAINT_PASSWORD=test
   - DIRECTOR_KICKSTART=false
```

Do you have any idea how to fix it on your image ?
