### ISSUE TITLE
webdevops/php-nginx-dev and XDebug

### ISSUE THREAD

**Issue by djSeverin** [webdevops/Dockerfile#184]
Hello Team.

I've so far had no luck with webdevops/php-nginx-dev and XDebug.

Docker swarm config - docker-compose.yml 
```
version: "3"
services:
  api:
    image: webdevops/php-nginx-dev:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./application/api:/app
    environment:
      - PHP_DISPLAY_ERRORS=1
      - WEB_DOCUMENT_ROOT=/app/html
      - PHP_DEBUGGER=xdebug
      - XDEBUG_REMOTE_AUTOSTART=1
      - XDEBUG_REMOTE_CONNECT_BACK=1
      - XDEBUG_REMOTE_PORT=9090
      - XDEBUG_REMOTE_HOST=<my host machine's IP address>
    networks:
      - network
```

Executed with:

> docker stack deploy testStack --compose-file docker-compose.yml

No matter what I try, I can't get XDebug to talk to PHPStorm, configured with XDebug port 9090.

I've tried:
- XDebug Helper in a browser;
- Appending ?XDEBUG_SESSION_START=docker to the URL in postman.

In the odd chance the fault was PHPStorm, I tried with a vagrant machine and no problems.

Totally stumped. Can you provide any insight I may have missed?

**Comment by aahmadts** [comment]
I installed xDebug on `php-nginx:5.6` using adding this lines to my Dockerfile . I hope this works for your also.

`RUN cd /var/www && \
	wget https://xdebug.org/files/xdebug-2.5.5.tgz && \
	tar -xzf xdebug-2.5.5.tgz && cd xdebug-2.5.5 && \
	/usr/local/bin/phpize && \
	./configure --enable-xdebug &&\
	make && \
	currentDir=$(pwd) && \
	extensionsDir=$(php-config --extension-dir) && \
	cp $currentDir/modules/xdebug.so $extensionsDir  &&\
	touch /var/log/xdebug.log &&\
	rm -R /var/www/xdebug*`

**Comment by djSeverin** [comment]
This was a configuration error on my part. The correct configuration for my case was:

Docker swarm config - docker-compose.yml 
```yaml
version: "3"
services:
  api:
    image: webdevops/php-nginx-dev:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./application/api:/app
      - ./configs/php.ini:/opt/docker/etc/php/php.ini
    environment:
      - PHP_DISPLAY_ERRORS=1
      - WEB_DOCUMENT_ROOT=/app/html
      - PHP_DEBUGGER=xdebug
    networks:
      - network
```

Created a php.ini file in my application directory named `./configs/php.ini` containing:

```ini
xdebug.remote_host=192.168.0.15 # <-- IP address of host running the IDE
xdebug.remote_port=9010 # <-- Port the IDE debug has been configured to listen on

xdebug.default_enable=On
xdebug.remote_enable=On
xdebug.remote_autostart=On
xdebug.remote_connect_back=Off
xdebug.profiler_enable=On
xdebug.remote_handler=dbgp
xdebug.remote_log="/app/xdebug.log"
xdebug.max_nesting_level=1256
xdebug.idekey="PHPSTORM"
```

The key to sorting this out was adding the `xdebug.remote_log` line. This created the file `xdebug.log` in the application directory when php executed that made clear xdebug was not able to connect back to the host.
