### ISSUE TITLE
PHP is not enabled in image (php-apache:centos-7)

### ISSUE THREAD

**Issue by lauriskuznecovs** [webdevops/Dockerfile#204]
PHP is not configured for Apache, so php scripts are displayed as plain text.
Looks like **/etc/httpd/conf.d/** does not have any php .conf files

Inside container:
```
[root@115a0d59fa0a /]# php -v
PHP 5.4.16 (cli) (built: Nov  6 2016 00:29:02)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
```

My **docker-compose.yml** looks following:
```
version: '3'

services:
  webserver:
    image: webdevops/php-apache:centos-7
    ports:
      - 8080:80
    volumes:
      - ./:/app
```
