### ISSUE TITLE
How to add more vhost in one server Apache?

### ISSUE THREAD

**Issue by rifton007** [webdevops/Dockerfile#216]
Hi all and thanks you for your assitance.
I create my first docker-compose.yml and it works correctly with image `webdevops/php-apache:debian-8-php7`. But now I need to add a lot vhost in my apache server and Docker displays this message 
`AH00526: Syntax error on line 1 of /opt/docker/etc/httpd/vhost.common.d/vhost.conf:`
`<VirtualHost> cannot occur within <VirtualHost> section`

Do you know why ?
*my docker-compose.yml*
```
web:
    image: webdevops/php-apache:debian-8-php7
    volumes:
        - d:/dev/www:/var/www/html
        - d:/dev/vhost.conf:/opt/docker/etc/httpd/vhost.common.d/vhost.conf
    ports:
        - "80:80"
    environment:
        - WEB_DOCUMENT_ROOT=/var/www/html
        - PHP_DISPLAY_ERRORS=1
```
*my vhost.conf*
```
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /var/www/html
</VirtualHost>

<VirtualHost *:80>
    ServerName project1.dev
    DocumentRoot /var/www/html/project1/public
</VirtualHost>
<VirtualHost *:80>
    ServerName project2.dev
    DocumentRoot /var/www/html/project2/public
</VirtualHost>
```
And if you need the guide of the image that I use:
http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-apache-dev.html#apache-layout

*Thanks all for your help*
