### ISSUE TITLE
Session Problem in Alpine

### ISSUE THREAD

**Issue by morcegon** [webdevops/Dockerfile#223]
In php-apache-dev:alpine the sessions aren't persisting. Every time a page is loaded the sessions is empty. The same code in debian works fine.

**Comment by hhoechtl** [comment]
Basically sessions work. I tested it using the following simple example
```yaml
version: '2'
services:
  app:
    image: webdevops/php-apache-dev:alpine
    links:
      - mailhog
    volumes:
      - ./app/:/app/
    environment:
      - VIRTUAL_HOST=app.docker
      - VIRTUAL_PORT=80
```

```php
<?php
// Start Session
session_start();
// Show banner
echo '<b>Session Support Checker</b><hr />';
// Check if the page has been reloaded
if(!isset($_GET['reload']) OR $_GET['reload'] != 'true') {
   // Set the message
   $_SESSION['MESSAGE'] = 'Session support enabled!<br />';
   // Give user link to check
   echo '<a href="?reload=true">Click HERE</a> to check for PHP Session Support.<br />';
} else {
   // Check if the message has been carried on in the reload
   if(isset($_SESSION['MESSAGE'])) {
      echo $_SESSION['MESSAGE'];
   } else {
      echo 'Sorry, it appears session support is not enabled, or you PHP version is to old. <a href="?reload=false">Click HERE</a> to go back.<br />';
   }
}
```

And this works.

What application are you running and could it be, that you configured redis session save_handler or something like that and redis is not running?
