### ISSUE TITLE
Permission problem with application user  set in docker-compose.yml (webdevops/php-nginx-dev)

### ISSUE THREAD

**Issue by akos-vomo** [webdevops/Dockerfile#226]
Hi,

I'm using the image `webdevops/php-nginx-dev:7.1` and I've set the user in my docker compose file to `application`. When building it for the first time, it's OK, but when I stop the container, and start it again, it exits with the following error:

`error: failed switching to "root": operation not permitted`

Here is my config:
```yaml
version: '2'
services:
  php:
    image: webdevops/php-nginx-dev:7.1
    user: "application"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - XDEBUG_REMOTE_AUTOSTART=On
      - XDEBUG_PROFILER_ENABLE=On
      - XDEBUG_REMOTE_HOST=192.168.0.145
      - XDEBUG_REMOTE_PORT=9001
      - PHP_DEBUGGER=xdebug
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
# ...
```
The issue is similar to #219.

Do you have any suggestions? (Removing the user from the compose file, and supplying `-u` parameter to `exec` is not an option.) 

Thank you.
