### ISSUE TITLE
Question: Best way to run commands after booting the container?

### ISSUE THREAD

**Issue by siewert87** [webdevops/Dockerfile#246]
Hey,

thank you for your awesome docker images!

I've this in my docker-compose.yml:

```yml
php:
    image: webdevops/php-dev:7.2
    depends_on:
        - db
    volumes:
        - .:/var/www/html
    working_dir: /var/www/html
    user: application
```

I'm using this image for symfony-apps and need to install dependencies and some other things after initializing the container.

Where is the best place to do that? Using `command` overrides the default command. Using `entrypoint`overrides the default entrypoint, so what to do?

Best,
Christian
