### ISSUE TITLE
Ansible container should have working directory other than root (and run with non-privileged user)

### ISSUE THREAD

**Issue by bittner** [webdevops/Dockerfile#266]
We're using the [webdevops/ansible](https://hub.docker.com/r/webdevops/ansible/tags/) image for deploying files using Ansible on GitLab CI. The path things are executed in inside the container is `/` (root folder), the executing user is `root`.

Now, Ansible complains that the directory executing is word-writable and skips evaluating the `ansible.cfg` file:

```python
 [WARNING] Ansible is being run in a world writable directory (/builds/vshn/ansibleplaybookexample), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'
 [WARNING]: Could not match supplied host pattern, ignoring: dev

PLAY [Foobarbaz test deployment] ************************
skipping: no hosts matched

PLAY RECAP *********************************************************************
```

Looks like it would make sense to make the working directory something else than the root folder (e.g. `/home/ansible`). While at it, maybe it also makes sense to make a non-privileged run inside the container (e.g. a user `ansible`), which is also [recommended](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user) according to the Dockerfile best practices.

Just for reference, a sample GitLab CI configuration looks like this:

```yaml
image: webdevops/ansible
before_script:
  # taken from: https://gitlab.com/help/ci/ssh_keys/README.md
  - mkdir -pv ~/.ssh && chmod -v 700 ~/.ssh
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts && chmod -v 644 ~/.ssh/known_hosts
variables:
  ANSIBLE_STDOUT_CALLBACK: debug
script:
  ansible-playbook playbook.yml --limit dev
```

**Comment by hhoechtl** [comment]
We use:

```yaml
deploy:live:
  image: 1drop/php-70-docker-utils
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - NOW=$(date -u +"%Y%m%d%H%M%SZ")
    - composer install --no-dev --no-interaction --no-progress --ignore-platform-reqs -d app
    - ansible-playbook -i ci/hosts_live -e "ansistrano_release_version=$NOW" ci/deploy_live.yml
```

and commit the inventory inside the repository. On a fresh Gitlab runner nothing exists outside of `/builds/vendor/project/jobid` (or however they build the directory structure. Therefore a `/etc/ansible/hosts` could not be present inside the `webdevops/ansible` based runner.

As a Gitlab CI runner is ephemeral, the best practices don't really apply as it's no ongoing production usage. Many docker images like composer, nodejs and other tools run as gitlab ci runner containers with the user root and that's usually not a problem.

The whole topic regarding the usage of `USER` as well in Dockerfiles as within Kubernetes, etc. is still a big issue and I'm already looking for somebody who could help me with this issue, because I didn't quite understand why the entire `gosu` approach was implemented (which causes these issues or impossibilities). See https://github.com/webdevops/Dockerfile/issues/226
