### ISSUE TITLE
Add wait-for-it.sh script or similar to liquibase images

### ISSUE THREAD

**Issue by aairey** [webdevops/Dockerfile#306]
Hello,

With docker-compose version 3.0 and higher, is no longer possible to add a healthcheck to a database service and set a conditional `depends_on`.
See: https://docs.docker.com/compose/compose-file/#depends_on

As per https://docs.docker.com/compose/startup-order/, we can use a script that waits for the database service to be healthy.
To avoid creating my own fork of the webdevops image, I thought it might be useful to include this script in the mysql and postgresql versions of the image.
It could be optional to use it (so not having it as the default entrypoint or cmd ...), but at least have it inside the image.

**Comment by hhoechtl** [comment]
Which image are you referring to? We don't build database images.

**Comment by aairey** [comment]
The liquibase images.

**Comment by marklagendijk** [comment]
The liquibase image could indeed benefit from this.
A common use case is that you want Liquibase to run when you start the services in your `docker-compose.yaml`.

Currently it is quite tricky to get this working correctly. I will add my working example here:

`docker-compose.yaml`:
``` yaml
version: "3"
services:
  postgres:
    image: postgres:10
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data-volumes/postgres/:/var/lib/postgresql/data/
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
  liquibase:
    image: webdevops/liquibase:postgres
    restart: 'no'
    depends_on:
      - postgres
    volumes:
      - ./docker/liquibase/:/scripts/
    command:
      - /scripts/wait-for-it.sh
      - postgres:5432
      - --
      - /scripts/init.sh
```

`docker/postgres/init.sql`:
``` sql
CREATE DATABASE my_database;
\connect local_federation;
CREATE SCHEMA liquibase;
```


`docker/liquibase/wait-for-it.sh`: [wait-for-it.sh](https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh)

`docker/liquibase/init.sh`:
``` bash
/opt/liquibase/liquibase \
    --driver=org.postgresql.Driver \
    --url=jdbc:postgresql://postgres:5432/my_database \
    --liquibaseSchemaName=liquibase \
    --classpath=/usr/share/java/postgresql.jar \
    --changeLogFile=/liquibase/my-changelog.xml \
    --username=postgres \
    --password= \
    --contexts=all \
    update
```
