### ISSUE TITLE
Question -> help wanted (run .sh on container start)

### ISSUE THREAD

**Issue by AleksejJur** [webdevops/Dockerfile#344]
Hello I'm new to Docker
so I can't understand how to run my .sh files on docker container start

I'm using php-nginx-dev:7.4 and linked it with mysql container. It works. But when I copying .sh files into container and try to run docker-compose up it ignores .sh script

Trying to do this way

Dokerfile
```
FROM webdevops/php-nginx-dev:7.4
COPY test.sh /app/test.sh
RUN chmod +x /app/test.sh
CMD ["/bin/bash", "-c", "/app/test.sh && supervisord"]
```

docker-compose

```
version: '3'

services:
    php-nginx-dev:
        container_name: php-nginx-dev
        build: php-nginx-webdev
        ports:
            - "80:80"
        volumes:
            - ./src:/app
            - ./nginx/config/default.conf:/opt/docker/etc/nginx/main.conf
        depends_on:
          - mysql

    mysql:
        container_name: mysql
        image: mysql:8
        restart: always
        ports:
            - "3306:3306"
```
