### ISSUE TITLE
How can I activate xdebug on php-nginx-dev:7.4?

### ISSUE THREAD

**Issue by wilcorrea** [webdevops/Dockerfile#349]
It works on php-nginx-dev:7.3, but it doesn't works on php-nginx-dev:7.4

**Comment by hhoechtl** [comment]
I just tried and it works. Can you please provide a reproducible example?

**Comment by wilcorrea** [comment]
Sorry the late

When I am using the 7.3 the phpstorm recognizes xdebug, when I change the image on docker-compose to 7.4 phpstorm says "no debug extension loaded". 

![image](https://user-images.githubusercontent.com/803733/79410413-b7847080-7f76-11ea-81f0-edd7e9ec03f4.png)

My docker-compose.yml
```yaml
  # api
  app-nginx:
    image: webdevops/php-nginx-dev:7.4
    container_name: app-nginx
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - ./laravel:/var/www/app
      - .docker/falcon-nginx/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - falcon-mysql
      - falcon-redis
    links:
      - falcon-mysql
      - falcon-redis
    environment:
      - PHP_DEBUGGER=xdebug
      - WEB_DOCUMENT_ROOT=/var/www/app/public
    expose:
      - 9090
    ports:
      - 80:80
```

The entire docker-php-ext-xdebug.ini is overwritten for debugging purposes
https://gist.github.com/wilcorrea/d72fc089ceaa6029079ccb9512c1854f
