### ISSUE TITLE
webdevops/php-nginx-dev postfix configuration problem

### ISSUE THREAD

**Issue by DamianoP** [webdevops/Dockerfile#365]
I'm trying to configure a production system using "webdevops/php-nginx". 
My goal is just to have outgoing emails and I am not interested in incoming emails.
Reading here #220 I discovered that postfix is present only in the image "webdevops/php-nginx-dev" and is not present in "webdevops/php-nginx" .
However when I try to send emails with the php in the log I read several error messages related to postfix
For example:

connect to alt1.gmail-smtp-in.l.google.com[2a00:1450:4010:c03::1a]:25: Cannot assign requested address
connect to alt1.gmail-smtp-in.l.google.com[209.85.233.26]:25: Connection timed out

This is my docker compose for the websites
```
version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mypass"
    expose:
      - "3306"
    volumes:
      - /mypath/:/var/lib/mysql/
    restart: always
  webApp:
    image: webdevops/php-nginx-dev:7.4
    restart: always
    volumes:
      - "/mywebsite1/:/usr/share/nginx/html"
    environment:
      - WEB_DOCUMENT_ROOT=/usr/share/nginx/html/publicFolder
      - VIRTUAL_HOST=mypublicsite.domain.com
      - VIRTUAL_PORT=80
    expose:
      - 80
    depends_on:
      - db
  webAppNumber2:
    image: webdevops/php-nginx-dev:7.4
    restart: always
    volumes:
      - "/mywebsite2/:/usr/share/nginx/html"
    environment:
      - WEB_DOCUMENT_ROOT=/usr/share/nginx/html/publicFolder
      - VIRTUAL_HOST=mypublicsiteNumber2.domain.com
      - VIRTUAL_PORT=80
    expose:
      - 80
    depends_on:
      - db
networks:
  default:
    external:
      name: nginx-proxy
```

This is my proxy configuration
```
version: '3.6'
services:
  nginx:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
networks:
  default:
    external:
      name: nginx-proxy
```
The proxy works very well, both sites are perfectly reachable and https is enabled.
The only problem is that I can't get them to send emails (for example the e-mails of successful registration to the website1 or the website2).
The machines are on an Amazon EC2 instance and port 25 is open.

My php mail function is the easiest one:
```
<?php
mail(to,subject,message,headers,parameters);
?>
```
