### ISSUE TITLE
[QUESTION] How to properly configure certbot with autorenewal?

### ISSUE THREAD

**Issue by cod3rshotout** [webdevops/Dockerfile#367]
Hi,

I'm using your `webdevops/php-apache:alpine-php7` image for implement a `LAMP` environment and until now everything is working smoth.

I would like to ask, if someone could share an example about certbot. I saw that do you also have `webdevops/certbot` but unfortunately there is no documentation [here](https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/certbot.html). 
So I really doesn't know where to start.

Actually my lamp configuration is the following:

```
version: "3"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "80:80"
    volumes:
      - ./www:/app
      - ./php.ini:/opt/docker/etc/php/php.ini
      - ./sites-available:/opt/docker/etc/httpd/vhost.common.d
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "8088:80"

  certbot:
    image: webdevops/certbot
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
```

as you can see I have four containers, and the last one is `certbot`.  My concern are this:

- How can I request a certificate for my subdomain which I've actually stored inside `sites-available` folder that is mounted as volume of `web` container?

- How can I set a cron job or something like a task that auto renew all the certificates?

- How can I store in a volume the obtained certificates?

Kind regards

**Comment by hhoechtl** [comment]
Sorry don't know either, but I usually use traefik or nginx reverse proxy in combination with letsencrypt companion.

**Comment by cod3rshotout** [comment]
@hhoechtl Could you show me a way to achieve this using your Docker image in combination of a cron job that auto renew the certs?

Thanks

**Comment by kaluzki** [comment]
> @hhoechtl Could you show me a way to achieve this using your Docker image in combination of a cron job that auto renew the certs?
> 
> Thanks

## .env
```env
DB_USER=root
DB_PASSWORD=root
AUTH=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/
INTERN=intern.example.com
```

## docker-compose.yml
```yaml
version: '3.7'

x-:
  traefik: &traefik
    traefik.enable: true

services:

  data:
    image: busybox
    network_mode: "none"
    restart: "no"
    volumes:
      - data:/data
    command: sh -c "chmod -Rv 600 /data/*"

  proxy:
    depends_on:
      - data
    image: traefik:2.4
    hostname: proxy
    restart: unless-stopped
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/data
    ports:
      - 80:80
      - 443:443
    command:
      #      - "--log.level=debug"
      #      - "--api.debug=true"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.80.address=:80"
      - "--entrypoints.443.address=:443"
      - "--certificatesresolvers.certs.acme.storage=/data/acme.json"
      - "--certificatesresolvers.certs.acme.httpchallenge.entrypoint=80"
    labels:
      <<: *traefik
      traefik.http.middlewares.redirect-https.redirectscheme.scheme: https
      traefik.http.middlewares.redirect-https.redirectscheme.permanent: true
      traefik.http.middlewares.auth.basicauth.users: $AUTH

      traefik.http.routers.80-proxy.service: api@internal
      traefik.http.routers.80-proxy.entrypoints: 80
      traefik.http.routers.80-proxy.rule: Host(`$INTERN`)
      traefik.http.routers.80-proxy.middlewares: redirect-https@docker
      traefik.http.routers.443-proxy.middlewares: auth
      traefik.http.routers.443-proxy.service: api@internal
      traefik.http.routers.443-proxy.entrypoints: 443
      traefik.http.routers.443-proxy.tls: true
      traefik.http.routers.443-proxy.tls.certresolver: certs
      traefik.http.routers.443-proxy.rule: Host(`$INTERN`)


  mysql:
    image: xampp/mysql
    hostname: mysql
    restart: unless-stopped
    networks:
      - net
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD

  pma:
    image: phpmyadmin/phpmyadmin
    hostname: pma
    restart: unless-stopped
    networks:
      - net
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql

    labels:
      <<: *traefik
      traefik.http.routers.80-pma.entrypoints: 80
      traefik.http.routers.80-pma.rule: Host(`pma.$INTERN`)
      traefik.http.routers.80-pma.middlewares: redirect-https@docker
      traefik.http.routers.443-pma.entrypoints: 443
      traefik.http.routers.443-pma.tls: true
      traefik.http.routers.443-pma.tls.certresolver: certs
      traefik.http.routers.443-pma.rule: Host(`pma.$INTERN`)

  mail:
    image: mailhog/mailhog:v1.0.1
    hostname: mail
    restart: unless-stopped
    networks:
      - net

    labels:
      <<: *traefik
      traefik.http.services.80-mail.loadbalancer.server.port: 8025
      traefik.http.routers.80-mail.service: 80-mail
      traefik.http.routers.80-mail.entrypoints: 80
      traefik.http.routers.80-mail.rule: Host(`mail.$INTERN`)
      traefik.http.routers.80-mail.middlewares: redirect-https@docker
      traefik.http.routers.443-mail.middlewares: auth
      traefik.http.routers.443-mail.entrypoints: 443
      traefik.http.routers.443-mail.tls: true
      traefik.http.routers.443-mail.tls.certresolver: certs
      traefik.http.routers.443-mail.rule: Host(`mail.$INTERN`)


volumes:
  data:
  mysql:

networks:
  net:
    name: ${NET_NAME:-intern}
```
