### ISSUE TITLE
webdevops/php-apache-dev:7.3-alpine - error: failed switching to "root": operation not permitted

### ISSUE THREAD

**Issue by pedro-laviano-turing** [webdevops/Dockerfile#407]
Hi,

I'm using the image `webdevops/php-apache-dev:7.3-alpine`. When building it for the first time, it's OK, but when I stop the container, and start it again, it exits with the following error:

error: failed switching to "root": operation not permitted

Here is my config:

```
version: '3'
services:
    web:
        image: webdevops/php-apache-dev:7.3-alpine
        container_name: web
        restart: always
        user: application
        environment:
          - WEB_ALIAS_DOMAIN=magento.environment.local
          - WEB_DOCUMENT_ROOT=/app/pub
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=2048M
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=500M
          - PHP_UPLOAD_MAX_FILESIZE=1024M
        volumes:
          - /c/path/to/magento:/app:cached
        ports:
          - "80:80"
          - "443:443"
          - "32823:22"
...
```

Do you have any suggestions? How can I get it up and running again?

Thank you.
