### ISSUE TITLE
running php artisan queue:work 

### ISSUE THREAD

**Issue by redcore-developer** [webdevops/Dockerfile#447]
Hi, 

I would like to have an idea if how can I run laravel queue. Thanks

**Comment by hhoechtl** [comment]
You basically add a worker container which starts the `queue:work` command. By doing this it won't start nginx and php-fpm (supervisor.d).

```yaml
services:
  worker:
    restart: always
    environment:
      CLI_SCRIPT: /app/artisan
    command: ["cli", "queue:work"]
```
