### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

### ISSUE THREAD

**Issue by turbovladimir** [webdevops/Dockerfile#527]
Hello team! I'm using your images long time. I found it very helpful. But now I met  an error **net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)** in my browser, that thing affects my javascripts and... maybe... something else. 
So I decided to understand how it happened and discovered that it happens when I'm using image **webdevops/php-nginx-dev:8.2** with developer tools like xDebug. If I change it on **webdevops/php-nginx:8.2**  the problem is solved. I hope you guys help me to figure it out =)

Here is my docker configs
```
services:
  broker-dev:
    platform: linux/amd64
    container_name: c-broker-dev
    depends_on:
      - postgrest-dev
      - postgrest-test
    image: 'app_dev'
    build:
        context: ../
        args:
          APP_ENV_FILE: .env
          IMAGE: webdevops/php-nginx-dev:8.2
    working_dir: /app
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    security_opt:
      - seccomp:unconfined
    ports:
      - '${APP_PORT_DEV:-8080}:80'
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      PHP_DISPLAY_ERRORS: 1
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 55375
      XDEBUG_START_WITH_REQUEST: 'yes'
      PHP_IDE_CONFIG: serverName=xdebug_server
      DATABASE_URL: "postgresql://app:1234@c-postgres-dev:5432/broker?serverVersion=16&charset=utf8"
      DATABASE_TEST_URL: "postgresql://app:1234@c-postgres-test:5432/broker_test?serverVersion=16&charset=utf8"
    volumes:
      - ../:/app
    networks:
      default:
        ipv4_address: 172.30.0.5
```

Dockerfile:
```
ARG IMAGE

FROM $IMAGE
ADD . /app
WORKDIR /app
ARG APP_ENV_FILE

RUN chmod 755 -R . \
    && chown application:application -R . \
    && cat $APP_ENV_FILE > .env \
    && rm -rf .env.* \
    && ls -la \
    && cat .env

USER application
```
