### ISSUE TITLE
How to use variable CLI_SCRIPT?

### ISSUE THREAD

**Issue by 18601673727** [webdevops/Dockerfile#65]
Hi there, I'm trying to use `image: webdevops/php:alpine-3` with env variable `CLI_SCRIPT` via docker-compose.yml configured in below ways then type `docker-compose up` to run but found out both of them seemed doesn't been executed at all.
```yml
environment:
  - CLI_SCRIPT="echo 1234567"
``` 
or
```yml
volumes:
  - ./command:/tmp/command
environment:
  - CLI_SCRIPT="/tmp/command/test.sh"
```
Am I doing it wrong?
